version: "3"

services:
  # JupyterLab
  jupyter:
    image: jupyter/datascience-notebook:65761486d5d3

    command: start.sh jupyter lab

    ports:
      - 8888:8888

    working_dir: /home/jovyan/work

    volumes:
      - .:/home/jovyan/work
