version: "3.7"

services:
  # Rails 샘플 애플리케이션
  app:
    build: .

    init: true

    ports:
      - "3000:3000"

    volumes:
      - .:/app
      # node_modules은 이미지에 있는 것을 사용
      - /app/node_modules
