version: "3"

services:
  app:
    image: ubuntu:18.04
    working_dir: /app
    volumes:
      - host-app:/app

volumes:
  host-app:
    driver_opts:
      type: nfs
      o: "addr=host.docker.internal,actimeo=1"
      device: ":${PWD}"
