version: "3"

services:
  # Sinatra 샘플 애플리케이션
  app:
    build: .

    command: ruby app.rb -o 0.0.0.0

    volumes:
      - .:/app
      - app-bundle:/usr/local/bundle

volumes:
  # Bundler로 설치한 gem 보관 볼륨
  app-bundle: