version: "3"

services:
  # JupyterLab
  jupyter:
    image: jupyter/datascience-notebook:65761486d5d3

    command: start.sh jupyter lab

    ports:
      - 8888:8888

    working_dir: /home/jovyan/work

    volumes:
      - .:/home/jovyan/work

    # 사용자 정보 변경. root 사용자로 기동
    user: root

    # 이 값들을 호스트 환경의 로그인 유저와 맞게 설정해 둔다
    environment:
      - NB_UID=1001
      - NB_GID=1001
      - CHOWN_HOME=yes
