version: "2"

services:
  # JupyterLab
  jupyter:
    build: .

    # 암호는 `secret`
    command: >-
      start.sh jupyter lab
      --NotebookApp.password=sha1:8345a7533e93:c96cc038ba00386b56f6d5cc050b1b8234d4bd5d

    ports:
      - 8888:8888

    # DataLoader가 사용하는 공용 메모리 확보 
    shm_size: 4G

    working_dir: /home/jovyan/work

    volumes:
      - .:/home/jovyan/work

    # user로 지정하는 UID를 호스트 환경의 로그인 사용자와 맞게 설정해 둔다.
    user: "1000"

    group_add:
      - users

      # Visdom 서버
  visdom:
    build: .

    command: visdom --hostname 0.0.0.0

    ports:
      - 127.0.0.1:8097:8097
